import { createSlice } from "@reduxjs/toolkit";

const initialCounterState = { counter: 0, showCounter: true };

const counterSlice = createSlice({
  name: "counter",
  initialState: initialCounterState,
  reducers: {
    increment(state) {
      //we can mutate state when use TOOLKIT, cuz it clone existing state and behind the scenes dont mutate it
      state.counter++;
    },
    decrement(state) {
      state.counter--;
    },
    incrase(state, action) {
      state.counter = state.counter + action.payload; //payload is toolkit reserved word
    },
    toggleCounter(state) {
      state.showCounter = !state.showCounter;
    },
  },
});

export const counterActions = counterSlice.actions; //it return object with type property which have some unique autogenerated value

export default counterSlice.reducer;
